### PR TITLE
Fixing Issue #15

### PR DESCRIPTION
**Pull request by lsalazar1**
Issue #15 

Can you guys check if this will run better than our current code? I have a feeling it's going to be slower because it's having to use a for-loop and comparing each time.

### CODE REVIEW

**Comment by lsalazar1** [comment]
Capture

**Comment by rouoba** [comment]
if we are sure that after being plugged in, a sensor wont be removed or its echo(or pin) location won't be changed, we can save time by comparing only echo, or only trigger

**Comment by rouoba** [comment]
Also, in case we have a small number of sensors (like 9 in our case), the slowdown (if present) should be minimal.

**Review by rouoba — CHANGES_REQUESTED** [review]
Please refer to my comments for issue #15

**Comment by lsalazar1** [comment]
> if we are sure that after being plugged in, a sensor wont be removed or its echo(or pin) location won't be changed, we can save time by comparing only echo, or only trigger

Can you explain more haha? Are you saying that this is okay?

**Comment by rouoba** [comment]
Let's say we have 10 sensors, from SRC00 to SRC09. If each sensor after being plugged in keeps the same echo and trigger numbers, we can compare only the values of echo (or trigger if we want), knowing that each sensor retains the same couple values (trigger, echo)
Not sure if it makes more sense.

**Comment by lsalazar1** [comment]
@gazie91 @mbghazi Any thoughts? Dropping table vs checking if database exists?

We'd have a problem running this piece of code for overhead US, because the ```sensor``` object has hard coded threshold distances.

**Comment by lsalazar1** [comment]
> Let's say we have 10 sensors, from SRC00 to SRC09. If each sensor after being plugged in keeps the same echo and trigger numbers, we can compare only the values of echo (or trigger if we want), knowing that each sensor retains the same couple values (trigger, echo)
> Not sure if it makes more sense.

So lose the 'and' in the if-statement lol? xD

**Comment by rouoba** [comment]
yes

**Comment by mbghazi** [comment]
What about using "or" || instead of an "and" condition?

**Comment by lsalazar1** [comment]
Both could work. Which one should we go with?

**Comment by mbghazi** [comment]
I am leaning towards an Or statement because it offers us a little more flexibility

What do you think @rouoba @gazie91 ?

**Comment by rouoba** [comment]
We could, but if we are sure no pin position is changed, we can just check one pin

**Comment by mbghazi** [comment]
I think we all agree not to use recursion right?

**Comment by lsalazar1** [comment]
Recursion for what?

**Comment by rouoba** [comment]
huh, i thought recursion was your favorite lol

**Comment by mbghazi** [comment]
Instead of a for loop, that would just make our code more convoluted

How about a while loop, is there an exit condition we know 100% will work regardless of number of sensors we use?

**Comment by lsalazar1** [comment]
Can you write some pseudo code to explain it? I can't think of any exit conditions that we can use for a while-loop.

**Comment by mbghazi** [comment]
hmm, let me brainstorm on this...

**Comment by mbghazi** [comment]
@lsalazar1 can you post the psuedocode for this loop? would make it easier to reconstruct it

**Comment by rouoba** [comment]
>after the system is powered on, for each sensor:
>read its pin number, go through the collection and look for matching pin number. Take action accordingly whether a match is found
>stop after the last sensor

**Comment by lsalazar1** [comment]
I'll try but all of the docs I've seen regarding navigating MongoDB, uses for-loops. The reason I went with a for-loop is, because  I want to "do some things" **for each** document in a collection.

**Comment by lsalazar1** [comment]
Our next problem with this issue is it wouldn't work with the overhead sensors. The code calls an instance of DistanceSensor() which has the threshold distance hard-coded.

**Comment by mbghazi** [comment]
Wait, overhead would not work because.... it will only work with a certain distance already delineated?

**Comment by rouoba** [comment]
can you explain "overhead sensor"

**Comment by lsalazar1** [comment]
> can you explain "overhead sensor"

The L-part of your drawing lol

**Comment by rouoba** [comment]
oh lol

**Comment by mbghazi** [comment]
Remember when i talked about having sensors and the pi hang overhead the parking spots, with the ultrasonic sensors aimed downwards?

**Comment by rouoba** [comment]
yeah i got it now
sorry im multitasking hard over here

**Comment by lsalazar1** [comment]
Should we remove the killProgram() method in our class, have this fix?

**Comment by mbghazi** [comment]
Is there a place on git where we can store removed functions/snippets of code in case we might want to come back and refactor them in?

**Comment by lsalazar1** [comment]
We can revert back to a certain commit but we would lose all our commits made after that one. That would open us up for merge conflicts, which are a major pain to fix.

**Comment by mbghazi** [comment]
Then its better to branch out, then decide which one to merge back into the parent

**Comment by lsalazar1** [comment]
Right now we have this
* Master
* ------------- * Development
* -------------- * ---------------- * Issue-15

**Comment by mbghazi** [comment]
•	Master
•	------------- * Development
•	-------------- * ---------------- * Issue-15
•	-------------- * ---------------- * ---------------- * Issue-15 with killProgram() method
•	-------------- * ---------------- * ---------------- * Issue-15 without killProgram() method

**Comment by mbghazi** [comment]
Would that work?

**Comment by lsalazar1** [comment]
I feel like at that point our branches would be too complex. My mentors told me its just easier to leave it at three major levels: master, development, and feature.

Master is the main project.

Development is basically the rough draft before we officially release a version

Feature are just little changes we add along the way that we merge into Development.

**Comment by lsalazar1** [comment]
What we can do is keep it in for now. Then when we have a code review to merge the development branch to master, we can decide whether to keep it or not.

**Comment by mbghazi** [comment]
Maybe comment it out?

**Comment by lsalazar1** [comment]
Let's close out this PR first and open up a new issue for it.

**Comment by rouoba** [comment]
what about front end and back end branches?

**Comment by lsalazar1** [comment]
We can discuss the branch workflow next meeting. Explaining master, feature, and development branches without visual representation is tiring me out haha.

**Comment by rouoba** [comment]
Ok sounds good

**Review by mariahfont — APPROVED** [review]

**Review by rouoba — APPROVED** [review]

**Pull request merged**
